services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory-backend:local
    container_name: inventory-backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: ${DB_URI}
      CROSS_ORIGIN_URL: http://localhost:3000
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:7.0
    container_name: inventory-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: inventory
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  prometheus:
    image: prom/prometheus:latest
    container_name: inventory-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: inventory-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"   # browser: http://localhost:3001
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
