name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main
      - prod-deployment-setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_DEPLOYMENT_TOKEN }}

      - name: Create a new deployment
        run: doctl apps create-deployment ${{ secrets.DIGITAL_OCEAN_APP_ID }}
